//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bharatTGLGoldInOutDetail
    {
        public int GLInOutID { get; set; }
        public string RefType { get; set; }
        public Nullable<int> RefNo { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<System.DateTime> Date_time { get; set; }
        public Nullable<int> SDID { get; set; }
        public Nullable<int> KYCID { get; set; }
        public string GoldLoanNo { get; set; }
        public Nullable<int> PouchNo { get; set; }
        public string GLInOutMode { get; set; }
        public string InOutLoc { get; set; }
        public Nullable<int> LocName { get; set; }
        public string LocResiName { get; set; }
        public string LocDetails { get; set; }
        public Nullable<int> NarrationID { get; set; }
        public Nullable<int> InOutBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> FYID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CMPID { get; set; }
        public string isActive { get; set; }
    }
}
