//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSystemGeneratedEntryMaster
    {
        public int DJEID { get; set; }
        public string RefType { get; set; }
        public int RefNo { get; set; }
        public string ReferenceNo { get; set; }
        public string LoginID { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> FinancialyearID { get; set; }
    }
}
