//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    
    public partial class GL_SanctionDisburse_KYC_Details_RTR_Result2
    {
        public int KYCID { get; set; }
        public string CustomerID { get; set; }
        public string ApplicationNo { get; set; }
        public string AppliedDate { get; set; }
        public string ExistingCustomerID { get; set; }
        public string ExistingPLCaseNo { get; set; }
        public string Cdate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string MaritalStatus { get; set; }
        public string Gender { get; set; }
        public string BirthDate { get; set; }
        public int Age { get; set; }
        public string Spouse { get; set; }
        public string PANNo { get; set; }
        public string MobileNo { get; set; }
        public string TelephoneNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string Landmark { get; set; }
        public string NomineeName { get; set; }
        public string NomineeRelation { get; set; }
        public string NomAddress { get; set; }
        public Nullable<int> GID { get; set; }
        public Nullable<int> SDID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> RateperGram { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> Purity { get; set; }
        public Nullable<decimal> TotalGrossWeight { get; set; }
        public Nullable<decimal> TotalNetWeight { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> Totalvalue { get; set; }
        public Nullable<decimal> TotalRate { get; set; }
        public Nullable<decimal> EligibleLoanAmt { get; set; }
        public Nullable<decimal> NetLoanAmtSanctioned { get; set; }
        public Nullable<decimal> NetLoanPayable { get; set; }
        public string LoanType { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public string SchemeName { get; set; }
        public string MaximumLoanAmount { get; set; }
        public string Tenure { get; set; }
        public Nullable<decimal> EligibleLoanAmount { get; set; }
        public string SchemeProcessingType { get; set; }
        public decimal SchemeProcessingCharge { get; set; }
        public decimal SchemeProcessingLimit { get; set; }
        public Nullable<int> PreSanctionId { get; set; }
    }
}
