//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageActionUser
    {
        public int MessageActionUserID { get; set; }
        public Nullable<int> MessageActionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual MessageAction MessageAction { get; set; }
    }
}
