//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_PinCode
    {
        public int Pc_Id { get; set; }
        public string Pc_Desc { get; set; }
        public string Pc_AreaName { get; set; }
        public int Pc_CityId { get; set; }
        public int Pc_ZoneId { get; set; }
        public Nullable<System.DateTime> Pc_RecordCreated { get; set; }
        public Nullable<System.DateTime> Pc_RecordUpdated { get; set; }
        public Nullable<int> Pc_RecordCreatedBy { get; set; }
        public Nullable<int> Pc_RecordUpdatedBy { get; set; }
    
        public virtual tblCityMaster tblCityMaster { get; set; }
        public virtual Mst_PinCode Mst_PinCode1 { get; set; }
        public virtual Mst_PinCode Mst_PinCode2 { get; set; }
    }
}
