//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class new1bharatTGLGoldStock
    {
        public int StockId { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public Nullable<int> OpeningBalance { get; set; }
        public Nullable<int> TotalDeposit { get; set; }
        public Nullable<int> TotalRelease { get; set; }
        public Nullable<int> ClosingBalance { get; set; }
    }
}
