//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class newauthorize
    {
        public int FormAuthID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<bool> IsSave { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
