//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBankCash_PaymentDetails
    {
        public int BCPID { get; set; }
        public string RefType { get; set; }
        public int RefNo { get; set; }
        public string ReferenceNo { get; set; }
        public System.DateTime RefDate { get; set; }
        public int VoucherNo { get; set; }
        public int BankCashAccID { get; set; }
        public int PaidTo { get; set; }
        public Nullable<double> Amount { get; set; }
        public string ChqNo { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public string Narration { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> FinancialyearID { get; set; }
    }
}
