//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GLChargeMaster_Details
    {
        public int ID { get; set; }
        public int CID { get; set; }
        public double LoanAmtFrom { get; set; }
        public double LoanAmtTo { get; set; }
        public double Charges { get; set; }
        public string ChargeType { get; set; }
    }
}
