//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ResidenceVerification
    {
        public int Id { get; set; }
        public int PreSanctionId { get; set; }
        public string TransactionId { get; set; }
        public string ApplicationNo { get; set; }
        public Nullable<System.DateTime> DateofVisit { get; set; }
        public Nullable<System.TimeSpan> TimeofVisit { get; set; }
        public string CustomerId { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string PersonVisitedName { get; set; }
        public string RelationWithCustomer { get; set; }
        public string FamilyMemberDetails { get; set; }
        public Nullable<int> ResidingAtThisAddress_Years { get; set; }
        public Nullable<int> ResidingAtThisAddress_Months { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Designation { get; set; }
        public string EmployeeCode { get; set; }
        public string Comments { get; set; }
        public string BldgHouseName { get; set; }
        public string Road { get; set; }
        public string BldgPlotNo { get; set; }
        public string RoomBlockNo { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string Landmark { get; set; }
        public string Distance { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string Area { get; set; }
        public string ResidenceCode { get; set; }
        public string AddressCategory { get; set; }
        public string IsApproved { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_PreSanctionDetails tbl_PreSanctionDetails { get; set; }
    }
}
