//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserLogin
    {
        public int LoginID { get; set; }
        public string LoginUserType { get; set; }
        public string LoginUser { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string LoginTime { get; set; }
        public string LogoutTime { get; set; }
        public string TotalTime { get; set; }
        public string HostName { get; set; }
        public string HostIPAddr { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> BranchID { get; set; }
    }
}
