//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankMaster
    {
        public int BankID { get; set; }
        public string BankName { get; set; }
        public string Address { get; set; }
        public string Branch { get; set; }
        public string Contactperson { get; set; }
        public string ContactNo1 { get; set; }
        public string ContactNo2 { get; set; }
        public string BankAlias { get; set; }
    }
}
