//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreateCompanyMaster
    {
        public int CompID { get; set; }
        public string Name { get; set; }
        public string MailingName { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string PANNo { get; set; }
        public string TANNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Financialyear { get; set; }
    }
}
