//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPenaltySlabtMaster
    {
        public int PSlabID { get; set; }
        public string PenaltyType { get; set; }
        public string PenaltySlabName { get; set; }
        public double Interest { get; set; }
    }
}
