//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchemeTransMonth
    {
        public int SchemesID { get; set; }
        public int MonthsFrom { get; set; }
        public int MonthsTo { get; set; }
        public int TotalMonths { get; set; }
        public int EMI { get; set; }
    }
}
