//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStateMaster
    {
        public int StateID { get; set; }
        public string StateName { get; set; }
        public int countryID { get; set; }
        public string StateCode { get; set; }
    
        public virtual tbl_CountryMaster tbl_CountryMaster { get; set; }
    }
}
