//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGL_FormDetails
    {
        public int FormID { get; set; }
        public string FormName { get; set; }
        public string FormPath { get; set; }
        public string ParentID { get; set; }
        public string ToolTip { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
