//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLCashAuth_Denomination_Details
    {
        public int DenoId { get; set; }
        public Nullable<int> CAUTHID { get; set; }
        public Nullable<int> Serialno { get; set; }
        public string DenoRs { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string NoteNos { get; set; }
    }
}
