//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLCashAuth_ReceiptDetails
    {
        public int CARCPTID { get; set; }
        public Nullable<int> RcptID { get; set; }
        public Nullable<int> CAUTHID { get; set; }
        public Nullable<int> SDID { get; set; }
        public Nullable<int> KYCID { get; set; }
        public string GoldLoanNo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Receivedcash { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<decimal> Principal { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> PenalInterest { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<bool> Finalized { get; set; }
    }
}
