//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLExcessAmount_Login
    {
        public int ExcessLoginID { get; set; }
        public string GoldLoanNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<decimal> ExcessLoanAmount { get; set; }
        public string SanctionStatus { get; set; }
    }
}
