//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLInwardForm_GoldDetails
    {
        public int GoldInwardID { get; set; }
        public Nullable<int> InwordID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string InwardStage { get; set; }
        public string Inwardfrom { get; set; }
        public string InwardFromLocation { get; set; }
        public string StockLocation { get; set; }
    }
}
