//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLInterest_Details
    {
        public int InterestDetID { get; set; }
        public Nullable<int> ReceiptID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<int> AllDaysTillDate { get; set; }
        public Nullable<int> ROI { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> PrevOSInterest { get; set; }
        public Nullable<int> ROIRowID { get; set; }
    }
}
