//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLInwardForm_BasicDetails
    {
        public int InwordID { get; set; }
        public Nullable<int> Ref_No { get; set; }
        public string GLCaseNo { get; set; }
        public string InwardType { get; set; }
        public string InwardBy { get; set; }
        public Nullable<int> CMPId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> FYId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
