//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLKYC_DocumentDetails
    {
        public int DID { get; set; }
        public Nullable<int> KYCID { get; set; }
        public Nullable<int> Serialno { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string OtherDoc { get; set; }
        public string DocName { get; set; }
        public string ImagePath { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<int> Empld { get; set; }
        public string NameOnDoc { get; set; }
        public string ImageUrl { get; set; }
        public byte[] ImageName { get; set; }
    }
}
