//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLKYC_BasicDetails
    {
        public Nullable<int> KYCID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public int OperatorID { get; set; }
        public string ExistingCustomerID { get; set; }
        public string ExistingPLCaseNo { get; set; }
        public string AppFName { get; set; }
        public string AppMName { get; set; }
        public string AppLName { get; set; }
        public string AppPhotoPath { get; set; }
        public string AppSignPath { get; set; }
        public byte[] AppPhoto { get; set; }
        public byte[] AppSign { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Age { get; set; }
        public string Spouse { get; set; }
        public string Children { get; set; }
        public string PANNo { get; set; }
        public string MobileNo { get; set; }
        public string VerificationCode { get; set; }
        public string TelephoneNo { get; set; }
        public string EmailID { get; set; }
        public string SourceofApplication { get; set; }
        public string SourceSpecification { get; set; }
        public Nullable<int> DealerID { get; set; }
        public string BldgHouseName { get; set; }
        public string Road { get; set; }
        public string BldgPlotNo { get; set; }
        public string RoomBlockNo { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string Landmark { get; set; }
        public string Occupation { get; set; }
        public string OrganizationName { get; set; }
        public string PresentIncome { get; set; }
        public string OfficeAddress { get; set; }
        public string EmploymentType { get; set; }
        public string SpecifyEmployment { get; set; }
        public string IndustriesType { get; set; }
        public string SpecifyIndustries { get; set; }
        public string Designation { get; set; }
        public string NomFName { get; set; }
        public string NomMName { get; set; }
        public string NomLName { get; set; }
        public string NomRelation { get; set; }
        public string NomAddress { get; set; }
        public Nullable<int> LoanpurposeID { get; set; }
        public string SpecifyLoanPurpose { get; set; }
        public Nullable<int> FYID { get; set; }
        public Nullable<int> CmpID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string isActive { get; set; }
        public Nullable<int> SourceofApplicationID { get; set; }
    }
}
