//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLKYC_BasicDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TGLKYC_BasicDetails()
        {
            this.tbl_PreSanctionDetails = new HashSet<tbl_PreSanctionDetails>();
            this.Trans_KYCAddresses = new HashSet<Trans_KYCAddresses>();
            this.TGLPreSanctions = new HashSet<TGLPreSanction>();
        }
    
        public int KYCID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public int OperatorID { get; set; }
        public string ExistingPLCaseNo { get; set; }
        public string AppFName { get; set; }
        public string AppMName { get; set; }
        public string AppLName { get; set; }
        public byte[] AppPhoto { get; set; }
        public string ImageName { get; set; }
        public string ContentType { get; set; }
        public string KycType { get; set; }
        public short Gender { get; set; }
        public string CibilGender { get; set; }
        public string MaritalStatus { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int Age { get; set; }
        public string Spouse { get; set; }
        public string PANNo { get; set; }
        public string MobileNo { get; set; }
        public string TelephoneNo { get; set; }
        public string EmailID { get; set; }
        public string BldgHouseName { get; set; }
        public string Road { get; set; }
        public string BldgPlotNo { get; set; }
        public string RoomBlockNo { get; set; }
        public string Landmark { get; set; }
        public string Occupation { get; set; }
        public string OrganizationName { get; set; }
        public decimal PresentIncome { get; set; }
        public string IndustriesType { get; set; }
        public string Designation { get; set; }
        public string NomFName { get; set; }
        public string NomMName { get; set; }
        public string NomLName { get; set; }
        public string NomRelation { get; set; }
        public string NomAddress { get; set; }
        public int FYID { get; set; }
        public int CmpID { get; set; }
        public int BranchID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool isActive { get; set; }
        public int SourceofApplicationID { get; set; }
        public System.DateTime KYCDate { get; set; }
        public string ApplicationNo { get; set; }
        public string AdhaarNo { get; set; }
        public string ApplicantPrefix { get; set; }
        public string FatherPrefix { get; set; }
        public string MotherName { get; set; }
        public string Father_Spouse { get; set; }
        public string CKYCNo { get; set; }
        public string OccupationOther { get; set; }
        public string IndustryOther { get; set; }
        public string NomineeMobileNo { get; set; }
        public string NomineePanNo { get; set; }
        public string NomineeAdharNo { get; set; }
        public string Distance { get; set; }
        public int PinCode { get; set; }
        public string ResidenceCode { get; set; }
        public string AddressCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PreSanctionDetails> tbl_PreSanctionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trans_KYCAddresses> Trans_KYCAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TGLPreSanction> TGLPreSanctions { get; set; }
    }
}
