//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLOutwardForm_GoldDetails
    {
        public int GoldOutwardID { get; set; }
        public Nullable<int> OutwordID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> InwardRefNo { get; set; }
        public string OutwardTo { get; set; }
        public string OutwardToLocation { get; set; }
        public string StockLocation { get; set; }
    }
}
