//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGlReceipt_BasicDetails
    {
        public int RcptId { get; set; }
        public Nullable<int> SDID { get; set; }
        public Nullable<int> KYCID { get; set; }
        public string GoldLoanNo { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<decimal> BalanceLoanPayable { get; set; }
        public Nullable<decimal> BalanceLoanEligibility { get; set; }
        public Nullable<decimal> ROI { get; set; }
        public string ReceiptBookNo { get; set; }
        public string ReceiptNo { get; set; }
        public string ReceivedFrom { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> CLP { get; set; }
        public Nullable<decimal> CLI { get; set; }
        public Nullable<decimal> CLPI { get; set; }
        public Nullable<decimal> CLC { get; set; }
        public Nullable<decimal> CLO { get; set; }
        public Nullable<decimal> RcvCLP { get; set; }
        public Nullable<int> RecCLPAccID { get; set; }
        public Nullable<int> RecCLPNarID { get; set; }
        public Nullable<decimal> RcvCLI { get; set; }
        public Nullable<int> RecCLIAccID { get; set; }
        public Nullable<int> RecCLINarID { get; set; }
        public Nullable<decimal> RcvCLPI { get; set; }
        public Nullable<int> RecCLPIAccID { get; set; }
        public Nullable<int> RecCLPINarID { get; set; }
        public Nullable<decimal> RecCLC { get; set; }
        public Nullable<int> RecCLCAccID { get; set; }
        public Nullable<int> RecCLCNarID { get; set; }
        public Nullable<decimal> RcvTotal { get; set; }
        public Nullable<int> BankAccID { get; set; }
        public Nullable<int> CashAccID { get; set; }
        public Nullable<int> CollectedByID { get; set; }
        public Nullable<int> CashierID { get; set; }
        public Nullable<int> CashInOutID { get; set; }
        public Nullable<int> BCRID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string isActive { get; set; }
        public Nullable<int> FYID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CMPID { get; set; }
        public string Finalize { get; set; }
        public Nullable<System.DateTime> InterestFromDate { get; set; }
        public Nullable<System.DateTime> InterestToDate { get; set; }
        public Nullable<decimal> OSPrincipal { get; set; }
        public Nullable<decimal> OSInterest { get; set; }
        public Nullable<int> OSDays { get; set; }
        public Nullable<System.DateTime> IntrestRcvTillDate { get; set; }
        public Nullable<decimal> LastROI { get; set; }
        public Nullable<decimal> AdvInterestAmt { get; set; }
        public Nullable<System.DateTime> AdvInterestFromDate { get; set; }
        public Nullable<System.DateTime> AdvInterestToDate { get; set; }
        public Nullable<int> AdvInterestAccID { get; set; }
        public Nullable<decimal> TotalAdvInterestAmount { get; set; }
        public Nullable<decimal> OSAdvInterestAmount { get; set; }
    }
}
