//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLSmsHistory
    {
        public int HistoryID { get; set; }
        public Nullable<System.DateTime> Date_details { get; set; }
        public Nullable<int> SDID { get; set; }
        public string GoldLoanNo { get; set; }
        public Nullable<int> KYCID { get; set; }
        public Nullable<decimal> Outstanding { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<System.DateTime> LastReceivedDate { get; set; }
        public Nullable<int> RemainderType { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string SmsText { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> FYID { get; set; }
        public Nullable<int> CmpID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string isActive { get; set; }
    }
}
