//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLSanctionDisburse_GoldItemDetails
    {
        public int GID { get; set; }
        public Nullable<int> SDID { get; set; }
        public Nullable<int> KycId { get; set; }
        public int ItemID { get; set; }
        public int Purity { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> RateperGram { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string ImgItemPath { get; set; }
        public Nullable<decimal> Deduction { get; set; }
    
        public virtual Mst_PurityMaster Mst_PurityMaster { get; set; }
        public virtual tblItemMaster tblItemMaster { get; set; }
    }
}
