//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLSanctionDisburse_ChargesPostingDetails
    {
        public int ID { get; set; }
        public Nullable<int> SDID { get; set; }
        public string GoldLoanNo { get; set; }
        public Nullable<int> AccID { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> FYID { get; set; }
    }
}
