//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGLSanctionDisburse_ChargesDetails
    {
        public int CHID { get; set; }
        public Nullable<int> SDID { get; set; }
        public Nullable<int> ChargeDetailsID { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ChargeID { get; set; }
        public Nullable<int> Gstid { get; set; }
    
        public virtual TGLSanctionDisburse_ChargesDetails TGLSanctionDisburse_ChargesDetails1 { get; set; }
        public virtual TGLSanctionDisburse_ChargesDetails TGLSanctionDisburse_ChargesDetails2 { get; set; }
    }
}
