//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_KYCAddresses
    {
        public int ID { get; set; }
        public int KYCID { get; set; }
        public string AddressCategory { get; set; }
        public string ResidenceCode { get; set; }
        public string BuildingHouseName { get; set; }
        public string Road { get; set; }
        public string BuildingPlotNo { get; set; }
        public string RoomBlockNo { get; set; }
        public string NearestLandmark { get; set; }
        public string Distance_km { get; set; }
        public string PinCode { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public string Area { get; set; }
        public string ZoneId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual TGLKYC_BasicDetails TGLKYC_BasicDetails { get; set; }
    }
}
