//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trn_DocUploadDetails
    {
        public int Id { get; set; }
        public int DocUploadId { get; set; }
        public int DocumentTypeId { get; set; }
        public int DocumentId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string UploadFileBase64 { get; set; }
    
        public virtual Trn_DocumentUpload Trn_DocumentUpload { get; set; }
    }
}
