//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trn_DocumentUpload
    {
        public int DocId { get; set; }
        public int TransactionId { get; set; }
        public string TransactionNumber { get; set; }
        public System.DateTime DocDate { get; set; }
        public int KycId { get; set; }
        public string CustomerId { get; set; }
        public string ApplicationNo { get; set; }
        public string LoanAccountNo { get; set; }
        public string Comments { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<System.DateTime> RecordCreated { get; set; }
        public Nullable<System.DateTime> RecordUpdated { get; set; }
        public Nullable<int> RecordCreatedBy { get; set; }
        public Nullable<int> RecordUpdatedBy { get; set; }
    }
}
