//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSchemeMaster_EffectiveROI
    {
        public int ROIID { get; set; }
        public int SID { get; set; }
        public int NoofDefaultMonths { get; set; }
        public decimal EffROI { get; set; }
    
        public virtual TSchemeMaster_BasicDetails TSchemeMaster_BasicDetails { get; set; }
    }
}
