//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Category
    {
        public int usercateid { get; set; }
        public string name { get; set; }
        public Nullable<int> hierarchyid { get; set; }
        public Nullable<int> status { get; set; }
    }
}
