//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthorization
    {
        public int ID { get; set; }
        public int FormID { get; set; }
        public int UserID { get; set; }
        public bool isVisible { get; set; }
        public bool isEdit { get; set; }
        public bool isSave { get; set; }
        public bool isDelete { get; set; }
        public bool isView { get; set; }
        public bool isDefault { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string isActive { get; set; }
        public int ParentID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> BackDatedVoucher { get; set; }
    }
}
