//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFormAuthorisationDetail
    {
        public int ID { get; set; }
        public int FormID { get; set; }
        public int RecordID { get; set; }
        public string Usr { get; set; }
        public string Admin { get; set; }
        public string Supervisor { get; set; }
        public int FinancialYrID { get; set; }
    }
}
