//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWeb.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFormAuthentication
    {
        public int FormAuthID { get; set; }
        public int UserTypeID { get; set; }
        public int FormID { get; set; }
        public string Visible { get; set; }
        public string CanADD { get; set; }
        public string CanEDIT { get; set; }
        public string CanSave { get; set; }
        public string CanDelete { get; set; }
        public string CanView { get; set; }
        public string CanFinalize { get; set; }
    }
}
